name: BROAD

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master
jobs: # 工作流
  build:
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout # 步骤1
        uses: actions/checkout@v4 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v4 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Docusaurus
        run: pnpm run build

      - name: Use ssh
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HARE_TOKEN }}

      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.HARE_TOKEN }}
          publish_dir: ./build

