name: Hare Blog Action
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          pnpm install
          pnpm run-script build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.HareBlog }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: pnpm install && pnpm run build
